---
title: "Graphite storage issues"
output:
  html_document: default
  html_notebook: default
  word_document: default
date: "March 17, 2017"
---

A tray of graphite was dropped in the SPL. This analysis checks to see
whether there's a systematic bias on the secondaries in that tray from
touching the vial cap.

Need to look at:
* Large vs small vials: reactors 31-40,>=70 are 6mm tubes
* comparison to undropped samples

```{r}
suppressMessages(library(amstools))
suppressMessages(library(tidyverse))
library(odbc)
library(knitr)
library(readxl)
options(digits = 3)
```

```{r}

# Load file of dropped OSG nums
dropped <- read_excel("dropped graphite touched cap.xlsx")
dropped <- dropped$osg

# Get raw data for dropped samples from DB
query <- paste0("SELECT
mst_num, wheel, runtime, snics_raw.tp_num, osg_num, sample_name, 
	sample_type, ok_calc, le12c, he13_12, he14_12
	FROM snics_raw
	JOIN target ON target.tp_num = snics_raw.tp_num
	WHERE sample_type IN ('B', 'SS')
  AND osg_num IN (", paste(dropped, collapse = ","), ")")

db <- conNOSAMS()
rawdata <- dbGetQuery(db, query)
rawdata <- rawdata %>% mutate(rt = as.POSIXct(runtime)) %>%
  arrange(osg_num, mst_num)

# get results for dropped samples
data <- getQCData('01-01-2017', osg = dropped)

# get reactors for dropped samples
query <- paste0("SELECT
osg_num, gf_reactor as reactor 
	FROM graphite
	WHERE osg_num IN (", paste(dropped, collapse = ","), ")")

reactor <- dbGetQuery(db, query)

reactor <- mutate(reactor, tube = ifelse((reactor %in% 31:40) | reactor > 69, "6mm", "9mm"))
data <- inner_join(data, reactor)
```


```{r}
ggplot(rawdata, aes(rt, he14_12, color = wheel)) +
  geom_line() + geom_point() + facet_wrap(~osg_num, scales = "free") +
  ggtitle("Raw 14/12 measurements") + 
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
```

```{r}
data %>% 
  arrange(osg_num) %>% 
  mutate(f_modern = round(f_modern, digits = 3), 
         rep_err = round(rep_err, digits = 3)) %>%
  select(name, osg_num, wheel, f_modern, rep_err) %>%
  unite(f_modern, rep_err, col = "Fm", sep = " +- ") %>%
  kable()
```

```{r, fig.height=8, message=FALSE, warning=FALSE}
ggplot(data, aes(name, normFm, color = tube, shape = wheel)) +
  geom_pointrange(aes(ymin = normFm - frep_err, ymax = normFm + frep_err)) + 
  geom_point() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```


```{r, fig.height=8, message=FALSE, warning=FALSE}
ggplot(data, aes(name, sigma, color = tube, shape = wheel)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```